### ISSUE TITLE
Getting corrupted when using dogeoin-qt

### ISSUE THREAD

**Issue by thanosz** [Blockchains-Download/Dogecoin#1]
As per description, extracting the data and launching dogecoin-qt in linux (not portable) I get a message that the database is corrupted and that the chain needs to be re-downloaded from scratch

**Comment by JohnTHaller** [comment]
Did you download and use the dogecoin.conf file so the client is correctly setup to use this pruned blockchain? It's detailed on the homepage: https://blockchains.download/dogecoin/

**Comment by thanosz** [comment]
So, in macos I cannot find a dogecoin.conf. Tried `~/.dogecoin/dogecoin.conf` and `~/Library/Application Support/Dogecoin/dogecoin.conf `and does not work (the folders were created manually). 

On linux there is a `~/.config/Dogecoin `folder containing a  `Dogecoin-Qt.conf`. Again created a `dogecoin.conf` without success. 

The `Degecoin-Qt.conf` has `bPrune=false nPruneSize=3` amongst other settings in a `[General]` section. The respective file in macos seems to be `~/Library/Preferences/org.dogecoin.Dogecoin-Qt.plist` in an encoded format.

The documentation assumes Windows and degecoin-portable

**Comment by JohnTHaller** [comment]
I'm unfamiliar with bPrune and nPruneSize though I see them within the Bitcoin et al code. I believe those are the settings from the UI which were added after pruning became more popular. The important line in config is prune=2200 in the Windows version of the Dogecoin client. It is the equivalent of starting it with the -prune=2200 command line switch. I think you could try that with Dogecoin on both Linux and Mac.

**Comment by thanosz** [comment]
Thanks. Passing the option to the command line worked on macos (`open -a /Applications/Dogecoin-Qt.app --args  -prune=2200)` Should work in Linux.
